[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sigil"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["appdirs"]

[project.optional-dependencies]
json5 = ["pyjson5>=1.6"]
