name: Ruff & Test

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install deps
        run: uv pip install --system --break-system-packages -r requirements.txt
      - name: Run Ruff
        run: ruff check . --fix
      - name: Run tests
        run: pytest || echo "No tests yet, just a placeholder"
