name: Ruff & Test

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up virtualenv
        run: uv venv .venv
      - name: Install deps
        run: uv pip install -p .venv/bin/python -r requirements.txt
      - name: Run Ruff
        run: .venv/bin/ruff check . --fix
      - name: Run tests
        run: .venv/bin/pytest || echo "No tests yet, just a placeholder"
